#security:
#  oauth2:
#    client:
#      clientId: client
#      clientSecret: secret
#      scope: scope1, scope2, scope3, scope4
#      registered-redirect-uri: http://www.netkiller.cn

spring:
  security:
    user:
      name: admin
#      password: $2a$10$Cyj3hM39V34r5pMeQ.Y9peuUqYMBSvsJ7GTBgp4.stWaTtWMboYGS
#      roles:
#      - ROLE_ADMIN
      