server:
    port: 8082
#    servlet:
#        context-path: 

security:
  oauth2:
    client:
      clientId: sso
      clientSecret: secret
      accessTokenUri: http://localhost:8080/oauth/token
      userAuthorizationUri: http://localhost:8080/oauth/authorize
    resource:
      userInfoUri: http://localhost:8080/test/user/me
spring:
  thymeleaf:
    cache: false