server:
  port: 8085

spring:
  application:
    name: oauth2-server   # 应用名称
#  redis:
#    host: localhost
  thymeleaf:
        prefix: classpath:/templates/

logging:
  level:
#    org.springframework.web: DEBUG
    org.springframework.security: DEBUG  